#ifndef QDBUTGARDLIB_GLOBAL_H
#define QDBUTGARDLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QDBUTGARDLIB_LIBRARY)
#  define QDBUTGARDLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QDBUTGARDLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QDBUTGARDLIB_GLOBAL_H
